### ISSUE TITLE
Delete All

### ISSUE THREAD

**Issue by Prudhvi1997** [sudeepjaiswal/ASJTagsView#10]
If i want to delete all the tags at once, i am not able to do all. Please check it out.

**Comment by nelzaatari** [comment]
i was able to achieve it by doing

-(void)DeleteAllTAgs:(ASJTagsView *)tagView
{
    for (id view in tagView.subviews)
    {
      if ([view isKindOfClass:[ASJTag class]])
      {
          ASJTag * tag = (ASJTag *)view;
          [tagView deleteTag:tag.tagText];
      }
    }
}

**Comment by sdpjswl** [comment]
@Prudhvi1997 You can use `- (void)deleteAllTags;` method.
