### ISSUE TITLE
Horizontal support

### ISSUE THREAD

**Issue by mradzinski** [sudeepjaiswal/ASJTagsView#2]
I didn't get it to work. Is there any special property to set for the control to scroll horizontally?

If by any chances by saying horizontal you are referring to landscape then I guess you should update the readme file because whoever uses this expecting to get horizontal scrolling will get disappointed.

**Comment by sdpjswl** [comment]
Yes, I meant landscape; I'll make the change. The tags only scroll vertically at the moment. I'll try to make horizontal work in a future release.
