### ISSUE TITLE
How to hide delete button

### ISSUE THREAD

**Issue by kmuddapu** [sudeepjaiswal/ASJTagsView#4]
Hello Sudeep,

Thanks for the controller.

How to hide delete button?

**Comment by ghost** [comment]
Any updates about this issue?

**Comment by hiteshtrivedi** [comment]
Hi 

**Add following in "ASJTagsView.h"**

@property (nonatomic) BOOL isDeleteButtonRemove;

**NOW add below conding in  '- (ASJTag *)tagView" methos in "ASJTagsView.m"**

if (_isDeleteButtonRemove == true) {
        tagView.deleteButton.hidden = YES;
}

Thats it

not set property where you created object for ASJTagsView
like
tagAreaView?.isDeleteButtonRemove = true

**Comment by sdpjswl** [comment]
Thanks @hiteshtrivedi, implemented new property `showDeleteButton`.
