### ISSUE TITLE
[Crash] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITouch pointSize]: unrecognized selector sent to instance 0x119d457b0'

### ISSUE THREAD

**Issue by glennposadas** [sudeepjaiswal/ASJTagsView#8]
Hi, library is freakin good - better than the others. However though, Ive been experiencing this crash that I believe I can't solve and the reason is inside the library.

Please do note as well that I have tried to reproduce the crash in the demo but I failed.

Full logs:

> 2017-05-22 12:01:21.888177 xx[1840:540486] XPC connection interrupted
> 2017-05-22 12:01:23.278494 xx[1840:540033] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITouch pointSize]: unrecognized selector sent to instance 0x119d457b0'
> *** First throw call stack:
> (0x19382d1b8 0x19226455c 0x193834268 0x193831270 0x19372a80c 0x19965052c 0x19964facc 0x19975b17c 0x1997e340c 0x1997e3040 0x1997e2ba8 0x19a0331f8 0x1997e45a8 0x19a031e80 0x19a0321d0 0x19a032158 0x194286d10 0x19a032974 0x19a031b30 0x19a032580 0x19a03358c 0x1996f4328 0x1005ad45c 0x1996f07dc 0x1005ad35c 0x1005af4b0 0x19381e6c8 0x1005af364 0x1005aefc4 0x1005ae4f0 0x1000b41dc 0x1000b459c 0x1998d79cc 0x19989fefc 0x1998b046c 0x19a15e150 0x199b072d0 0x199b06b04 0x199b0665c 0x19a15e150 0x199b06598 0x19989fb7c 0x19989f4b0 0x19989db20 0x19989c638 0x199b1d11c 0x19970cb14 0x199b1cdd0 0x1997170c4 0x199712328 0x1996e2da0 0x199ecc75c 0x199ec6130 0x1937dab5c 0x1937da4a4 0x1937d80a4 0x1937062b8 0x1951ba198 0x19974d7fc 0x199748534 0x1000ad778 0x1926e95b8)
> libc++abi.dylib: terminating with uncaught exception of type NSException

Repro steps:

1. Make a Swift project and integrate the library.
2. Add two tags.
3. Go to background by tapping on the home button of the phone.
4. Switch back to the app.
5. Delete the two tags.
6. Add a new tag and see the app crashes.

Any ideas?

**Comment by sdpjswl** [comment]
I was able to reproduce the issue, UIFont property was given `assign`, and it was getting deallocated. Changing it to `strong` fixed the problem.
