### ISSUE TITLE
How to add tag in scroll view in fixed width view.

### ISSUE THREAD

**Issue by balkrishanyadav** [sudeepjaiswal/ASJTagsView#9]
I am using cell and  I have to add Tag view in UITableviewCell  with scroll...
So please suggest me solution with this control so i can use in my projects...

**Comment by sdpjswl** [comment]
[TableViewCellExample.zip](https://github.com/sdpjswl/ASJTagsView/files/7914172/TableViewCellExample.zip)
This can be a possible solution
